import { CycloneSystem, fetchGdacsCyclones } from './cyclone-tracker.service';

export interface WeatherPushAlert {
  id: string;
  region: string; // State or District Name
  severity: 'Red' | 'Orange';
  title: string;
  summary: string;
  systemName?: string;
  windSpeedKmph?: number;
  rainfallMm24h?: number;
  timestamp: string;
  isRead: boolean;
  source: 'GDACS (UN OCHA)' | 'IMD Satellite Feed' | 'Doppler Radar' | 'Local Operations Control';
}

const SAVED_REGIONS_KEY = 'bharat_saved_operational_regions_v1';
const ALERT_HISTORY_KEY = 'bharat_weather_push_alert_history_v1';
const DEFAULT_OPERATIONAL_REGIONS = ['Odisha', 'West Bengal', 'Andhra Pradesh', 'Tamil Nadu'];

class WeatherPushNotificationService {
  private savedRegions: string[] = [];
  private alertHistory: WeatherPushAlert[] = [];
  private listeners: Set<(alert: WeatherPushAlert) => void> = new Set();
  private notifiedAlertKeys: Set<string> = new Set();
  private checkIntervalTimer: any = null;

  constructor() {
    this.loadSavedRegions();
    this.loadAlertHistory();
    this.startRealtimeMonitoring();
  }

  // Load saved operational regions from localStorage or defaults
  public loadSavedRegions(): string[] {
    try {
      const stored = localStorage.getItem(SAVED_REGIONS_KEY);
      if (stored) {
        this.savedRegions = JSON.parse(stored);
      } else {
        this.savedRegions = [...DEFAULT_OPERATIONAL_REGIONS];
        this.saveRegions(this.savedRegions);
      }
    } catch {
      this.savedRegions = [...DEFAULT_OPERATIONAL_REGIONS];
    }
    return this.savedRegions;
  }

  public saveRegions(regions: string[]): void {
    this.savedRegions = Array.from(new Set(regions));
    try {
      localStorage.setItem(SAVED_REGIONS_KEY, JSON.stringify(this.savedRegions));
    } catch (e) {
      console.warn('Failed to save operational regions:', e);
    }
    // Check if new regions match any active real-time warnings
    this.checkCurrentWarnings(false);
  }

  public addRegion(region: string): void {
    if (!this.savedRegions.includes(region)) {
      this.saveRegions([...this.savedRegions, region]);
    }
  }

  public removeRegion(region: string): void {
    this.saveRegions(this.savedRegions.filter(r => r.toLowerCase() !== region.toLowerCase()));
  }

  public getSavedRegions(): string[] {
    return [...this.savedRegions];
  }

  // Load alert history & purge past false/mock notifications
  private loadAlertHistory(): void {
    try {
      const stored = localStorage.getItem(ALERT_HISTORY_KEY);
      if (stored) {
        const parsed: WeatherPushAlert[] = JSON.parse(stored);
        // Clean out any historical false/mock alerts
        this.alertHistory = parsed.filter(a => {
          const sysName = (a.systemName || '').toLowerCase();
          const title = (a.title || '').toLowerCase();
          const summary = (a.summary || '').toLowerCase();
          // Filter out mock systems that never existed as active real-time storms
          if (sysName.includes('dana') || sysName.includes('bob-05') || sysName.includes('bob-07') || sysName.includes('arb-02') || sysName.includes('asna')) {
            return false;
          }
          if (title.includes('dana') || title.includes('bob-05') || title.includes('bob-07')) {
            return false;
          }
          if (summary.includes('dana') || summary.includes('dhamra port')) {
            return false;
          }
          // Filter out automatic default state alerts generated by static defaults
          if (title.includes('Heavy Severe Weather in Odisha') || title.includes('Heavy Severe Weather in West Bengal') || title.includes('Heavy Severe Weather in Andhra Pradesh')) {
            return false;
          }
          return true;
        });
        this.saveAlertHistory();
      } else {
        this.alertHistory = [];
      }
    } catch {
      this.alertHistory = [];
    }
  }

  public clearAlertHistory(): void {
    this.alertHistory = [];
    try {
      localStorage.removeItem(ALERT_HISTORY_KEY);
    } catch (e) {
      console.warn('Failed to clear alert history:', e);
    }
    // Notify in-app subscribers with null alert to clear banner
    this.listeners.forEach(cb => cb(null as any));
  }

  private saveAlertHistory(): void {
    try {
      localStorage.setItem(ALERT_HISTORY_KEY, JSON.stringify(this.alertHistory.slice(0, 50)));
    } catch (e) {
      console.warn('Failed to save alert history:', e);
    }
  }

  public getAlertHistory(): WeatherPushAlert[] {
    return [...this.alertHistory];
  }

  // Request native browser Push Notification permissions
  public async requestBrowserPushPermission(): Promise<NotificationPermission> {
    if (!('Notification' in window)) {
      return 'denied';
    }
    if (Notification.permission === 'granted') {
      return 'granted';
    }
    return await Notification.requestPermission();
  }

  public getBrowserPushPermissionStatus(): NotificationPermission | 'unsupported' {
    if (!('Notification' in window)) return 'unsupported';
    return Notification.permission;
  }

  // Synthesize emergency alert sound tone using Web Audio API
  public playEmergencyAlertTone(severity: 'Red' | 'Orange'): void {
    try {
      const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
      if (!AudioCtx) return;

      const ctx = new AudioCtx();
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();

      osc.type = severity === 'Red' ? 'sawtooth' : 'sine';
      
      // Siren tone frequencies (880 Hz to 440 Hz oscillation)
      const now = ctx.currentTime;
      osc.frequency.setValueAtTime(severity === 'Red' ? 880 : 660, now);
      osc.frequency.exponentialRampToValueAtTime(440, now + 0.3);
      osc.frequency.exponentialRampToValueAtTime(severity === 'Red' ? 880 : 660, now + 0.6);

      gain.gain.setValueAtTime(0.3, now);
      gain.gain.exponentialRampToValueAtTime(0.01, now + 0.8);

      osc.connect(gain);
      gain.connect(ctx.destination);

      osc.start(now);
      osc.stop(now + 0.8);

      // Trigger haptic vibration if supported
      if ('vibrate' in navigator) {
        navigator.vibrate(severity === 'Red' ? [200, 100, 200, 100, 300] : [150, 100, 150]);
      }
    } catch (err) {
      console.warn('Audio feedback unavailable:', err);
    }
  }

  // Subscribe to real-time push alerts
  public subscribe(callback: (alert: WeatherPushAlert) => void): () => void {
    this.listeners.add(callback);
    return () => {
      this.listeners.delete(callback);
    };
  }

  // Dispatch push alert to subscribers and trigger native OS push
  public dispatchPushAlert(alert: WeatherPushAlert): void {
    // Add to alert history
    this.alertHistory.unshift(alert);
    this.saveAlertHistory();

    // Play alert sound tone
    this.playEmergencyAlertTone(alert.severity);

    // Trigger native OS push notification if granted
    if ('Notification' in window && Notification.permission === 'granted') {
      try {
        new Notification(`🚨 ${alert.severity.toUpperCase()} WEATHER WARNING: ${alert.region}`, {
          body: `${alert.title}\n${alert.summary}`,
          icon: '/favicon.ico',
          tag: alert.id
        });
      } catch (e) {
        console.warn('Browser Notification error:', e);
      }
    }

    // Notify in-app subscribers
    this.listeners.forEach(cb => cb(alert));

    // Dispatch DOM custom event for global App listener
    window.dispatchEvent(new CustomEvent('weather-push-alert', { detail: alert }));
  }

  /**
   * Check verified, currently active cyclones from GDACS affecting India (Bay of Bengal & Arabian Sea).
   * All-India default: sends warning to every Indian user regardless of state.
   * Strict anti-false-alarm rules:
   * 1. Never alerts on placeholder / mock data.
   * 2. Never alerts on historical or past/expired storms.
   * 3. Never alerts on Green / non-severe advisory storms.
   * 4. Only alerts on active Red or Orange storms threatening Indian seas/states.
   * 5. If no active storm meets criteria, zero alerts are sent.
   */
  public async checkCurrentWarnings(forceDispatch: boolean = false, liveCyclones?: CycloneSystem[]): Promise<void> {
    let cyclonesToCheck = liveCyclones;
    if (!cyclonesToCheck) {
      try {
        const feed = await fetchGdacsCyclones();
        cyclonesToCheck = feed.indianSystems || [];
      } catch (e) {
        console.warn('Unable to query GDACS for warning check:', e);
        cyclonesToCheck = [];
      }
    }

    const now = Date.now();

    // Filter strictly for genuinely active severe systems in Indian Basin
    const activeSevereCyclones = cyclonesToCheck.filter((cyclone) => {
      // Must be currently active
      if (!cyclone.isCurrent) return false;

      // Must be within active window (not elapsed)
      if (cyclone.toDate) {
        const toMs = new Date(cyclone.toDate).getTime();
        // If storm ended more than 24 hours ago, consider it dissipated
        if (toMs > 0 && (now - toMs > 24 * 3600 * 1000)) {
          return false;
        }
      }

      // Only Red or Orange alert levels qualify for emergency push notifications
      const isRed = cyclone.alertLevel.toLowerCase().includes('red');
      const isOrange = cyclone.alertLevel.toLowerCase().includes('orange');
      return isRed || isOrange;
    });

    // Broadcast to all Indian users for each active severe storm in Indian seas/states
    activeSevereCyclones.forEach((cyclone) => {
      const isRed = cyclone.alertLevel.toLowerCase().includes('red');
      const severity: 'Red' | 'Orange' = isRed ? 'Red' : 'Orange';

      const regionStr = cyclone.affectedStates.length > 0 
        ? cyclone.affectedStates.join(', ')
        : 'All-India Maritime & Coastal Sector';

      const key = `live-gdacs-cyclone-${cyclone.id}-${severity}-${cyclone.maxSustainedWindKmph}`;

      if (!this.notifiedAlertKeys.has(key) || forceDispatch) {
        this.notifiedAlertKeys.add(key);
        const alert: WeatherPushAlert = {
          id: `alert-cyc-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`,
          region: regionStr,
          severity,
          title: `${severity.toUpperCase()} CYCLONE ALERT: ${cyclone.name}`,
          summary: `${cyclone.bulletinSummary} Max sustained winds ${cyclone.maxSustainedWindKmph} km/h with gusts up to ${cyclone.peakGustsKmph} km/h. Threatening: ${regionStr}.`,
          systemName: cyclone.name,
          windSpeedKmph: cyclone.maxSustainedWindKmph,
          timestamp: new Date().toISOString(),
          isRead: false,
          source: 'GDACS (UN OCHA)'
        };
        this.dispatchPushAlert(alert);
      }
    });
  }

  // Trigger explicit test push drill for user manual verification
  public triggerTestPushAlert(regionName?: string, severity: 'Red' | 'Orange' = 'Red'): void {
    const region = regionName || this.savedRegions[0] || 'Coastal Sector';
    const isRed = severity === 'Red';

    const testAlert: WeatherPushAlert = {
      id: `test-push-${Date.now()}`,
      region,
      severity,
      title: `[SIMULATION DRILL] ${isRed ? 'RED ALERT' : 'ORANGE ALERT'}: Communication Check for ${region}`,
      summary: `Manual push notification drill initiated for operational sector ${region}. Native audio siren and push telemetry verified. (This is an operational simulation drill, not an active cyclone warning).`,
      systemName: `Simulated Drill (${severity})`,
      windSpeedKmph: isRed ? 85 : 55,
      rainfallMm24h: isRed ? 60 : 30,
      timestamp: new Date().toISOString(),
      isRead: false,
      source: 'Local Operations Control'
    };

    this.dispatchPushAlert(testAlert);
  }

  // Start real-time push polling (checks every 60 seconds against GDACS)
  private startRealtimeMonitoring(): void {
    if (this.checkIntervalTimer) return;
    
    // Initial check after 4 seconds once app loads
    setTimeout(() => {
      this.checkCurrentWarnings(false);
    }, 4000);

    // Periodically verify warnings against live GDACS feed every 60 seconds
    this.checkIntervalTimer = setInterval(() => {
      this.checkCurrentWarnings(false);
    }, 60000);
  }
}

export const weatherPushService = new WeatherPushNotificationService();
